package.json
src/index.ts
src/types.ts
tsconfig.json
tslint.json
yarn.lock

Added tslint and fixed linting errors
Also moved `tslint` into separate npm script `lint` so you can fix some lint errors using the following command:
```
npm run lint -- --fix
```

chore: Add tslint

---

README.md

Update README.md (Add node example)

---

package.json
src/index.ts
yarn.lock

dropped isomorphic-fetch in favor of cross-fetch.

now React Native compatible.

---

src/index.ts
src/types.ts

i am new to github and ts   ^_^
this is my first opensource pr, so thank for your review and comment!

feat(setHeader): add api to support set request header

---

src/index.ts
tests/index.test.ts

Add response status code to rawRequest's result

---

.circleci/config.yml

add `graphql` in CI as it is a peer dependency.

fix: build by installing peer dep in ci

---

.circleci/config.yml
package.json
src/index.ts
tests/index.test.ts
tsconfig.json

Fixes regression https://github.com/prismagraphql/graphql-request/issues/94
Fixes https://github.com/prismagraphql/graphql-request/issues/26

Revert: feat support parsed query

---

README.md

[![CircleCI](https://circleci.com/gh/prismagraphql/graphql-request.svg?style=shield)](https://circleci.com/gh/prismagraphql/graphql-request)
[![CircleCI](https://circleci.com/gh/prisma/graphql-request.svg?style=shield)](https://circleci.com/gh/prisma/graphql-request)

Update CircleCI badge URL

---

examples/cookie-support-for-node.ts

Added setting the global 'fetch'

docs: fix example by setting global fetch variable

---

src/index.ts
src/types.dom.ts

Fixes https://github.com/prisma-labs/graphql-request/issues/196

fix: add missing headers type import / export

---

package.json
yarn.lock

Fixes https://github.com/advisories/GHSA-r683-j2x4-v87g and https://github.com/prisma-labs/graphql-request/issues/326

fix: upgrade cross-fetch for https://github.com/advisories/GHSA-r683-j2x4-v87g

---

README.md

errorPolicy option 'all' works condition

chore(docs): add errorPolicy 'all' confition

---

src/graphql-ws.ts
src/index.ts
src/resolveRequestDocument.ts

ref: https://github.com/prisma-labs/graphql-request/issues/371

fix: issue 371

---

src/index.ts
src/types.ts
tests/general.test.ts

This addresses issues like #318

feat: let requestMiddleware override url

---

package.json
src/createRequestBody.ts
src/graphql-ws.ts
src/index.ts
src/parseArgs.ts
src/types.dom.ts
src/types.ts
tests/batching.test.ts
tests/signal.test.ts
yarn.lock

* This MR should be merged before #412.
* This is based on #410.

feat: upgrade typescript

---

src/index.ts

just a silly typo, can discard if too small

refactor: typo bathching -> batching

---

.vscode/settings.json
src/classes/ClientError.ts
src/classes/GraphQLClient.ts
src/entrypoints/main.ts
src/helpers/runRequest.ts
src/helpers/types.ts
src/lib/graphql-ws.ts
src/lib/graphql.ts
src/lib/http.ts
src/lib/prelude.ts
tests/__helpers.ts
tests/batching.test.ts
tests/errorPolicy.test.ts
tests/general.test.ts
tests/json-serializer.test.ts
tsconfig.json

closes #472
This PR goes beyond the fix and chases refactoring too.

fix: do not require index sig on vars

---

src/legacy/helpers/runRequest.ts
tests/fetch.test.ts

fix: append search params

---

.github/workflows/pr.yml
package.json
pnpm-lock.yaml

chore(ci): add publint

---

README.md

I'm writing to you as an active user and enthusiast of your npm package, graphql-request. First off, I want to express my gratitude for the incredible work you've put into developing and maintaining this package. It has been an invaluable tool for many developers, including myself.
Considering the increasing adoption of GraphQL and the rising popularity of graphql-request in recent years, I believe that providing users with this additional information can further solidify graphql-request as the go-to choice for GraphQL data fetching in the npm ecosystem.
Thank you for considering my proposal.

chore: add download trend

---

src/entrypoints/alpha/_Graffle.ts
src/entrypoints/alpha/__Graffle.ts
src/entrypoints/alpha/main.ts
src/entrypoints/alpha/scalars.ts
src/layers/1_Schema/Hybrid/types/Scalar/Scalar.ts
src/layers/1_Schema/Hybrid/types/Scalar/codec.ts
src/layers/1_Schema/Hybrid/types/Scalar/nativeScalarCodecs.ts
tests/_/customScalarCodecs.ts

feat: scalar constructor with inference

---

eslint.config.js
examples/config-fetch.ts
examples/config-http-headers.ts
examples/generated-clients/countries/Client.ts
examples/generated-clients/countries/Error.ts
examples/generated-clients/countries/Global.ts
examples/generated-clients/countries/Index.ts
examples/generated-clients/countries/Scalar.ts
examples/generated-clients/countries/SchemaBuildtime.ts
examples/generated-clients/countries/SchemaRuntime.ts
examples/generated-clients/countries/Select.ts
examples/generated-clients/countries/_.ts
examples/generated-clients/countries/__.ts
examples/raw.ts
package.json
src/cli/_helpers.ts
src/cli/generate.ts
src/entrypoints/alpha/scalars.ts
src/layers/2_generator/code/SchemaRuntime.ts
src/layers/2_generator/files.ts
src/lib/prelude.ts

feat(cli): generate from introspection

---

src/cli/generate.ts
src/layers/4_generator/__snapshots__/config.test.ts.snap
src/layers/4_generator/config.test.ts
src/layers/4_generator/config.ts
src/layers/4_generator/generate.test.ts
src/layers/4_generator/helpers/fs.ts
tests/_/fixtures/custom.graphql
tests/_/fixtures/schema.graphql
tests/_/helpers.ts

fix(generator): support any schema file name

---

src/layers/5_request/core.ts
src/layers/6_client/gql/gql.ts
src/layers/6_client/handleOutput.ts
src/layers/6_client/requestMethods/document.test.ts
src/layers/6_client/requestMethods/requestMethods.ts
src/layers/7_extensions/SchemaErrors/SchemaErrors.test.ts
src/layers/7_extensions/SchemaErrors/SchemaErrors.ts
src/layers/7_extensions/Throws/Throws.test.ts

Follow up work:
- runtime config
- static return types

improve(extension/schema-errors): move req runtime to ext

---

package.json
pnpm-lock.yaml
src/lib/typescript-formatter.ts
tests/e2e/e2e.test.ts

feat(generator): use prettier if present

---

src/layers/6_client/chainExtensions/scalar.test-d.ts
src/layers/6_client/chainExtensions/scalar.ts
src/lib/prelude.ts
tests/_/helpers.ts

feat(client): scalar statically validate sddm present

---

src/documentBuilder/InferResult/OutputField.ts
src/extensions/SchemaErrors/tests/fixture/graffle/modules/schema.ts
src/generator/generator/__snapshots__/generate.test.ts.snap
src/generator/generators/Schema.ts
src/layers/6_client/chainExtensions/scalar.test-d.ts
src/layers/6_client/chainExtensions/scalar.ts
src/lib/prelude.ts
src/types/Schema/__.ts
tests/_/fixtures/scalars.ts
tests/_/schemas/kitchen-sink/graffle/modules/schema.ts
tests/_/schemas/mutation-only/graffle/modules/schema.ts
tests/_/schemas/pokemon/graffle/modules/schema.ts
tests/_/schemas/query-only/graffle/modules/schema.ts
website/graffle/modules/Schema.ts

feat(client): scalar type checks name

---

src/extension/extension.ts
src/extensions/Introspection/Introspection.ts
src/extensions/Introspection/config.ts
src/extensions/Opentelemetry/Opentelemetry.ts
src/extensions/SchemaErrors/runtime.ts
src/extensions/Throws/Throws.ts
src/extensions/Upload/Upload.ts
src/layers/6_client/chainExtensions/anyware.ts
src/lib/prelude.test-d.ts
src/lib/prelude.ts
tests/_/SpyExtension.ts

Progresses https://github.com/graffle-js/graffle/issues/1236

feat(extension): integrate config concept

---

src/generator/config/__snapshots__/config.test.ts.snap
src/generator/config/config.test.ts
src/generator/config/config.ts
src/requestPipeline/RequestPipeline.ts

fix(generator): introspection respect options

---

examples/55_document-builder/document-builder_directive.ts
package.json
pnpm-lock.yaml
src/documentBuilder/SelectGraphQLMapper/nodes/5_Field.ts
src/documentBuilder/requestMethods/requestMethods.test.ts
src/extensions/SchemaErrors/injectTypenameOnRootResultFields.ts
src/extensions/SchemaErrors/tests/SchemaErrors.test.ts
src/lib/dump.ts
src/lib/grafaid/document.ts

feat(perf): graphql.web for smaller bundle

---

src/generator/config/config.test.ts
src/generator/config/config.ts
src/generator/config/configInit.ts
src/generator/config/defaults.ts
src/generator/generator/generate.test.ts
src/generator/helpers/moduleGenerator.ts

feat(generator): configure import extension

---

.github/actions/setup/action.yaml
bundle-sizes/config.js
dprint.json
eslint.config.js
src/extensions/Upload/Upload.test.ts
src/extensions/Upload/Upload.ts
tests/_/schemas/upload/schema.ts

fix(extension/upload): non-upload requests work too

---

src/generator/config/config.ts
src/generator/config/configInit.ts
src/generator/generator/generate.test.ts

feat(generator): custom headers on introspection request

---

src/client/client.test.ts
src/client/client.ts

feat(client): catch excess props on ctor
