src/index.ts, tests/index.test.ts
I've noticed this issue when working with the latest `graphql-js` server. It returns `content-type` with `charset=utf-8`:
```
Content-Type: application/json; charset=utf-8
```
I have checked GitHub API and it does so:
```shell
curl -i -X POST https://api.github.com/graphql
Content-Type: application/json; charset=utf-8
```
=> Fix response when content type contains charset

src/index.ts, src/types.ts, tests/index.test.ts
Closes #6
Finally found some time to prepare this PR
=> feat: Allow passing more options to fetch

src/index.ts
Currently text responses are not parsed correctly.
This PR turns this:
```sh
GraphQL Error (Code: 502):
{"response":{"0":"<","1":"h","2":"t","3":"m","4":"l","5":">","6":"\r","7":"\n","8":"<","9":"h","10":"e","11":"a","12":"d","13":">","14":"<","15":"t","16":"i","17":"t","18":"l","19":"e","20":">","21":"5","22":"0","23":"2","24":"
","25":"B","26":"a","27":"d","28":"
","29":"G","30":"a","31":"t","32":"e","33":"w","34":"a","35":"y","36":"<","37":"/","38":"t","39":"i","40":"t","41":"l","42":"e","43":">","44":"<","45":"/","46":"h","47":"e","48":"a","49":"d","50":">","51":"\r","52":"\n","53":"<","54":"b","55":"o","56":"d","57":"y","58":" ","59":"b","60":"g","61":"c","62":"o","63":"l","64":"o","65":"r","66":"=","67":"\"","68":"w","69":"h","70":"i","71":"t","72":"e","73":"\"","74":">","75":"\r","7 …
```
=> Fix text error handling

README.md, src/index.ts, src/types.ts, tests/index.test.ts
Closes #62
This implements a new `rawRequest` method to allow clients to access all of [the defined GraphQL response keys](http://facebook.github.io/graphql/October2016/#sec-Response-Format): `data`, `errors` and `extensions`. With the `request` method it is not possible to access the `extensions` key if it is included in the response.
The only difference to the `request` method is, instead of [returning `result.data`](https://github.com/graphcool/graphql-request/blob/master/src/index.ts#L35), `rawRequest` simply returns the raw `result` object (which may include `data` and `extensions`).
Because of the similarities, there is currently a lot of repetition. @schickling let me know if this is OK or if you'd like to abstract the repeated logic. `request` could just call `rawRequest` and …
=> Add raw request method

package.json, src/index.ts, tests/index.test.ts, tsconfig.json
Test with mock passes without the feature as `gql` return type is `any`. Hence, I had to write a test that depends on internet and might be flaky. We can work on providing for a better mock API.
=> feat: support parsed query

src/index.ts
When func. was refactored last time it returned resolved promise, now it returns
Promise, hense async not needed since no await is used anywhere inside
the body.
Here is reference to when async was needed
https://github.com/prisma-labs/graphql-request/blame/fcb46735ff6f825090d9327bc9e2e69e12abaf79/src/index.ts#L49
=> refactor: remove unused `async` keywords

package.json, src/index.ts, yarn.lock
It's better if polyfill will be included on the application level rather than having it included by each similar to this vendor package (each may include different polyfill, which turns into bloated app). In my case "cross-fetch" doesn't make sense because I use `@babel/polyfill`
=> feat: drop cross-fetch polyfill dep

src/index.ts
Useful to use the `Options`-object. Easier to import from the base file than doing `import { Options as GraphQLClientOptions } from 'graphql-request/dist/src/types'`
=> feat: export `Options` type

src/types.dom.ts
closes #103
Adding optional timeout property to fix typescript errors #103
=> feat(types): Add timeout property to RequestInit interface

README.md
I think it would be useful to have the setHeaders and setHeader functions documented somewhere. 
Not sure if this is the right place for them but I think auth is the most common use case.
=> chore(docs): mention setHeader

README.md, package.json, src/index.ts, src/types.ts, tests/__helpers.ts, tests/index.test.ts, yarn.lock
closes #176
Example:
```ts
import gql from 'graphql-tag'
await request('https://foo.bar/graphql', gql`...`)
```
If you don't actually care about using DocumentNode but just
want the tooling support for gql template tag like IDE syntax
coloring and prettier autoformat then note you can use the
passthrough gql tag shipped with graphql-request to save a bit
of performance and not have to install another dep into your project.
```ts
import { gql } from 'graphql-request'
await request('https://foo.bar/graphql', gql`...`)
```
BREAKING CHANGE:
`graphql-request` now requires `graphql` version 14.x or 15.x as a peer dependency.
`graphql-request` uses a TypeScript type from the `graphql` package such that if you are using TypeScript to build your project and you are using `graphql-request` but …
=> feat!: accept DocumentNode input

src/types.ts
=> fix: remove TS 3.8+ import type syntax

README.md
Adds an example to README for GraphQL mutations
=> docs: Add example for Mutations to README

src/index.ts
Setting the request headers via the `setHeaders` method is broken. `setHeaders` only accepted the type `Headers` which is not a pure object, so destructuring it would not append the headers when calling `fetch`. One option would be to restrict the type of headers to `Record<string, string>`. However, that doesn't seem like the direction this package is taking, so the only other option is to handle all possible cases, i.e. `Headers`, `string[][]`, `Record<string, string>` and `undefined`.
The PR also fixes the expected type of input to the `setHeaders` method, so it matches the type of `RequestInit["headers"]`.
Unfortunately, I wasn't able to meaningfully test the added transformation logic via unit tests. I'm open to suggestions here 🙂 
closes #203
=> fix: send headers from .setHeaders to server

README.md, examples/custom-fetch.ts, src/index.ts, src/types.dom.ts, tests/custom-fetch.test.ts
Supersedes  #178 
Kudos to @tarekrached for implementing the feature. I've added docs and tests as requested.
=> feat: support custom fetch with GraphQLClient constructor

.github/workflows/pr.yml, .github/workflows/trunk.yml, README.md, package.json, src/index.ts, tests/headers.test.ts
Couple things that have been done to avoid similar problem in future:
1. Use namespaced import style to avoid apparent references to global
Headers that are actually references to the imported TypeScript
interface.
2. Run tests in jsDOM and Node environments.
closes #206
=> fix: global Headers class reference

.github/workflows/pr.yml, .github/workflows/trunk.yml, README.md, package.json
=> feat: do not enforce node version

README.md
Wrote this to fix https://github.com/prisma-labs/graphql-request/issues/211 but also thought it might be nice to collapse the examples...
@jasonkuhrt let me know if it's nicer to you or should I just focus on the community section?
=> chore(docs): add community section and collapsable examples

README.md, examples/passing-custom-header-per-request.ts, src/index.ts, tests/headers.test.ts
closes #33
Support passing custom header per request.
The functions (request and rawRequest) are backward-compatible.
=> feat: Support per-request headers (#33)

src/index.ts, tests/general.test.ts
Fixes #245 
This adds `headers` to `ClientError` in `request` the same way that it is done for `rawRequest`:
https://github.com/prisma-labs/graphql-request/blob/5b233c5658e65ed0d98cf8bff50beec413f399b9/src/index.ts#L71-L73
=> fix: include headers in ClientError response (#245)

src/index.ts, tests/headers.test.ts
This will allow headers to be set on the exported request function.
=> feat: passthrough headers on exported request function

src/index.ts
I also formatted the request()'s argument list to look like the rest of the code, if you don't mind.
=> fix: remove errors from rawRequest return type (#174)

.github/workflows/pr.yml, .github/workflows/trunk.yml
1. node v10 and v15 are deprecated. node v16 is released. 
2. Upgrade `actions/setup-node` from `v1` to `v2`.
=> chore(ci): refresh node version matrix

src/index.ts
1. `rawRequest` can be reused in `request`
2. `rawRequest` returns `Promise<{ data: T; extensions?: any; headers: Dom.Headers; status: number }>` instead of `Promise<{ data?: T; extensions?: any; headers: Dom.Headers; status: number }>` (difference between `data?: T` and `data: T`). `data` cannot be undefined, as it'd be guarenteed by the spec.
=> refactor: remove duplicate code

src/index.ts
🖖🏻  Hello Prisma team,
Here is a proposal to provide support for GET requests.
Should resolve #61 and #260
=> feat: add support for get request

src/types.ts
The type signature of `GraphQLError` is not 100% correct, as far as I see:
1. It is common to have `extensions` on each error, which is currently not allowed
2. `locations` and `path` are currently required, but should probably be optional, as you _can_ have errors without them
=> fix: types on GraphQLError

src/createRequestBody.ts, src/index.ts, tests/__snapshots__/gql.test.ts.snap, tests/gql.test.ts
We use the operation name for tracking purposes on our API. However, as already discussed here: https://github.com/prisma-labs/graphql-request/issues/64, the operationName is currently not send.
In contrast to issue https://github.com/prisma-labs/graphql-request/issues/64, which is about allowing to define an operationName when sending multiple queries at once, this is about sending the `operationName` field in the payload sent to the API for "regular" queries/mutations like this:
```gql
query allUsers {
users
}
```
Where I want the server to use `allUsers` for tracking purposes. When we send the `operationName` field in our payload, like e.g. Apollo or some other GraphQL clients do, it can easily be used by GraphQL server implementations. This should be a completely backwards compatible …
=> feat: add operationName to payload if defined in gql

README.md
Just a minor typo fix: `Typescript` -> `TypeScript`.
=> chore(docs): fix TypeScript spelling

src/index.ts
This is useful when importing types from type definition files.
Makes this work:
```ts
import { RequestDocument, Variables } from 'graphql-request';
```
rather than having to do something like:
```ts
import { RequestDocument, Variables } from 'graphql-request/dist/types';
```
=> feat(types): export more client types

src/index.ts, tests/general.test.ts
Changed the `Content-Type` response header detection to be case-insensitive in the [getResult ](https://github.com/prisma-labs/graphql-request/blob/f5f7286748943665f969082dbe91aed3195e8b7a/src/index.ts#L537)function.
Fixes: #314
=> fix: case-insensitive 'Content-type' response header detection

package.json
#311 details how source maps are broken - they refer files in the `src` directory which aren't included in the installed package.
This is the easiest fix for this problem. There is no fix which doesn't increase the size of the package other than completely removing the source maps unfortunately.
I've taken this approach rather than embedding the source in the map files as that's what we decided elsewhere in the graphql ecosystem: https://github.com/graphql/graphiql/pull/2047
=> fix: include source files in package for source maps

README.md, src/index.ts, tests/general.test.ts
Following [a previous PR](https://github.com/prisma-labs/graphql-request/pull/280) from another contributor that allowed getting the `OperationName` from a GQL operation, I added the possibility to also get it when the document is a string.
Currently, `operationName` could only be extracted from "regular" queries/mutations, and it wouldn't work for operations passed as strings.
In our current project, all our queries and mutations are auto-generated, and they all are strings, hence the `operationName` was never resolved and passed.
I just used the `parser` exposed by `graphql` to get the actual operation from the string, then used the existing logic for getting and setting the operationName if found.
=> feat: parse string documents to extract the operationName

src/index.ts
Following PR #280 which added `operationName` to the payload in `request()`,  this PR adds `operationName` to the payload in `rawRequest()`.
Currently, `operationName` is [explicitly passed](https://github.com/prisma-labs/graphql-request/blob/master/src/index.ts#L230) as `undefined` to the request body. We would like to be able to reap the benefits offered by `rawRequest()` while also being able to pass `operationName` in the request body.
=> feat: include operationName to rawRequest payload if defined in gql

README.md, package.json, src/createRequestBody.ts, src/defaultJsonSerializer.ts, src/index.ts, src/types.dom.ts, tests/general.test.ts, tests/json-serializer.test.ts
**Context**
If you need to support numeric values larger than [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), you can't use built-in JSON.parse/JSON.stringify.
> While most JSON parsers assume numeric values have same precision restrictions as IEEE 754 double, JSON specification does not say anything about number precision. Any floating point number in decimal (optionally scientific) notation is valid JSON value. It's a good idea to serialize values which might fall out of IEEE 754 integer precision as strings in your JSON api, but { "value" : 9223372036854775807}, for example, is still a valid RFC4627 JSON string, and in most JS runtimes the result of JSON.parse is this object: { value: …
=> feat: custom JSON serializer support

README.md, src/index.ts, src/types.ts, tests/headers.test.ts
Continuation of https://github.com/prisma-labs/graphql-request/pull/91#issuecomment-1096658311
This is just a small, incomplete showcase of my train of thought.
I see a few ways do do this:
Option 1: The code in this PR is the "naive" version in the sense that as you can see in src/index.ts I'm just going over each occurrence of `Dom.RequestInit['headers']` and replacing it with `original Dom type | dynamic type` which is not very elegant, and muddles the actual dom types - which is why I'm not very keen on the `Record<string, string | () => string` approach from the original PR from a few years ago.
Option 2: What would be potentially more elegant is just `Dom.RequestInit['headers'] | () => Dom.RequestInit['headers']`, which does not add any further union types to the already existing …
=> feat: dynamic headers

src/types.ts
I'm getting `Type 'GraphQLError' is missing the following properties from type 'GraphQLError': nodes, source, positions, originalError, and 3 more.` when some other type uses a real `GraphQLError`
=> fix: use GraphQLError from `graphql` module

README.md
This adds a sample implementation of @toinelin's #277, since the ability to make GET requests was otherwise not documented.
Note that you have to specifically pass in a `jsonSerializer`, or it'll break trying to stringify the query parameters:
```js
const graphQLClient = new GraphQLClient(endpoint, {
method: 'GET',
jsonSerializer: {
parse: JSON.parse,
stringify: JSON.stringify,
},
});
```
This took me a while to figure out, so I thought this would make for a good addition to the docs. Should probably default to `defaultJsonSerializer` though.
=> chore(docs): add Readme section for GET requests

src/index.ts
This module supports [using a custom fetch method](https://github.com/prisma-labs/graphql-request#using-a-custom-fetch-method), which is great when fetch is not supported in a given environment.
However, `resolveHeaders` function does not have into account that `cross-fetch` might be undefined. This was creating problems for me when using this module in a Cloudflare worker with the error: `TypeError: Right-hand side of 'instanceof' is not an object`.
This should have tests to avoid regressions, but at this point is quite complex to setup a test environment for this. I would suggest we can use something like https://github.com/hugomrdias/playwright-test and run tests in a service worker, but I left this for a follow up PR as I am not sure about how you would prefer to deal with this.
=> fix: resolve headers when cross fetch is not available in environment

README.md
The example quickstart graphql query to api.graph.cool movies was not working.
I have replaced it with a query to the public spacex graphql api.
Also running autoformat on README.md which re-organizes the table of contents section to match the existing README.md structure.
=> chore(docs): Replacing the quickstart gql query example

src/index.ts, src/types.ts, tests/general.test.ts
I really like the new middleware feature and would like to use it for some basic error handling.
Unfortunately, the current implementation only invokes the middleware if the fetch request has been resolved, meaning it will never get called on request failure.
BREAKING CHANGE:
Middleware will get either the response or error now, whereas before it would only get the response and never run in the error case.
=> feat!: Invoke responseMiddleware in error cases as well

src/index.ts, src/types.ts, tests/general.test.ts
Currently, it's not possible to pass any async data to request middlewares. For example, fetching and auth token. I think using `Promise.resolve` is the cleanest solution and shouldn't add any noticeable overhead to non async middlewares.
=> feat: Allow async requestMiddleware

README.md
Update GraphQL Code Generator related part of `README` following our new recommendations for front-end/client usage: https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue
=> chore(docs): update documentation on GraphQL Code Generator integration

src/index.ts, tests/general.test.ts
Hi All,
This adds the `application/graphql+json` ( some servers use this) and the new standard `application/graphql-response+json` content types ( https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#serialization-format ) which will help stop new users to this library trying to figure out why request is throwing an error for a valid query.
Let me know if I need to change anything
Thanks!
=> fix #388,#373 add application/graphql+json and application/graphql-response+json content type

README.md, src/index.ts, tests/typed-document-node.test.ts
For more information, see #409. I hope I didn't miss something but this simplifies the signature of `client.request` and `request` while also fixing the issue that a missing `variables` is not being type checked by TypeScript. The changes in `README.md` are only because someone forgot to run `yarn format` before pushing, maybe a hook running it automatically before commiting would make sense if this occurs regularly.
=> fix: `variables` not being required by ts (#409)

src/index.ts, src/types.ts
- This is a follow up to #398
- As discussed, we should merge the typescript update (#411) before this one 
- This is based on #410
=> feat: pass `operationName` and `variables` to `requestMiddleware`

src/index.ts, tests/__helpers.ts, tests/general.test.ts
Hello,
We have a project called courses 3 which is a learning management system. In this project, we started using UltraGraphQL as the back end. We have encountered error responses after making correct requests from the front end using the 'request' function from graphql-request. After checking out the error, it seems that the response had no error, but the function evaluated it otherwise. In the next sample, you can see the error which we have printed out from the front end. 
`Error: GraphQL Error (Code: 200): {"response":{"extensions":{},"data":{"courses_User":[{"courses_lastName":["Admin"],"courses_email":["admin@admin.admin"]}],"@context":{"_type":"@type","courses_email":"http://www.courses.matfyz.sk/ontology#email","courses_User":"http://www.courses.matfyz.sk/ontology#User","_id":"@id …
=> fix: check if property errors from response is an empty array

README.md, package.json
I tried to use `graphql-request` for a ReactNative app. But build errors occured because metro bundler unfortunately does not support `exports` field yet... 
So I would like to restore `main` field which was dropped by https://github.com/facebook/metro/issues/670.
This change would only restore backward compatibility and would not have any bad effect on modern environments.
=> feat: restore `main` field of package.json for environments that do not support `exports` field

README.md
This updates the TOC. Seems that for the last PR the `build:docs` script hadn't been run. This PR fixes that and removes the two items no longer present in the readme.
Wrt our conversation here: https://github.com/jasonkuhrt/graphql-request/pull/526#issuecomment-1552453800:
> Can you please update the docs about this topic. Just remove them. Also please make a new issue to remove main once the Metro issue is closed. Thanks!
> Would it be possible to expand that to current tooling that is still using main? I'm still waiting on the resolve package to add support for parsing exports for example.
> yep please create that issue or chime into existing one if there, thanks!
I could not find any follow up issue in this repo for removing main, so I'll consider the matter resolved. I suppose the …
=> chore(docs): regenerate TOC

src/types.ts
this fix https://github.com/jasonkuhrt/graphql-request/issues/428
=> fix: Add ClientError to ResponseMiddleware param

src/index.ts
This type is used in the @graphql-codegen/typescript-graphql-request package.
=> feat: export GraphQLClientRequestHeader

src/graphql-ws.ts
This PR adds support for TypedDocumentNodes to be passed to the `subscribe` and `request` methods of the WebSockets implementation.
This allows the return type from `next` and `variables` to be properly typed when paired with @graphql-codegen/cli
I have tested this change in my codebase and it appears to function as I would expect on the type level
=> fix: add support for TypedDocumentNode to be passed to WS methods

.github/workflows/pr.yml
Updates the workflow in CI to use the latest long-term support versions of Node.js (v18 & v20).
=> chore(ci): update Node.js versions to latest LTS

README.md
Since Node.js 20 has [reached LTS status](https://nodejs.org/en/blog/release/v20.9.0) the list of supported versions has changed, this PR updates them accodingly.
=> chore(docs): update supported Node.js versions in README

README.md, examples/configuration-request-json-serializer.ts, examples/other-middleware.ts, src/index.ts, src/parseArgs.ts, src/resolveRequestDocument.ts, tests/__helpers.ts, tests/batching.test.ts, tests/document-node.test.ts, tests/general.test.ts, tests/gql.test.ts, tests/graphql-ws.test.ts
Some mis-formatted code was previously committed, this PR fixes up the formatting issues.
=> fix: ensure code formatting is correct

src/index.ts, src/types.ts, tests/headers.test.ts
=> fix: do not overwrite user-provided `Content-Type` header

src/index.ts, src/parseArgs.ts, src/types.ts, tests/headers.test.ts
=> feat!: replace `GraphQLClientRequestHeaders` with built-in `HeadersInit` type

src/constants.ts, src/index.ts, tests/__snapshots__/document-node.test.ts.snap, tests/__snapshots__/gql.test.ts.snap, tests/general.test.ts, tests/headers.test.ts
Adds the `Accept` header to all requests with a [spec-compliant mime-type](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#accept). This PR also does some code cleanup and removes support for the legacy `application/graphql+json` mime type.
Closes #140
=> feat!: add spec compliant default `Accept` header

package.json, pnpm-lock.yaml, src/cli/generate.ts
This PR introduces a CLI for generating the client.
=> feat: introduce a CLI for generating the client

package.json, pnpm-lock.yaml, src/ResultSet/ResultSet.ts, src/Schema/Field/Field.ts, src/Schema/Field/Type.ts, src/Schema/NamedType/Enum.ts, src/Schema/NamedType/InputObjet.ts, src/Schema/NamedType/Interface.ts, src/Schema/NamedType/NamedType.ts, src/Schema/NamedType/Object.ts, src/Schema/NamedType/Union.ts, src/Schema/NamedType/_.ts, src/Schema/__.ts, src/SelectionSet/SelectionSet.test-d.ts, src/SelectionSet/SelectionSet.ts, src/generator/generator.ts, tests/ts/_/schema.graphql, tests/ts/_/schema.ts, tests/ts/__snapshots__/generate.test.ts.snap
This PR brings support for Input Objects in selection sets.
=> feat(ts): support input object in selection set

package.json, src/ResultSet/ResultSet.test-d.ts, src/Schema/Index.ts, src/Schema/NamedType/Scalar/Scalar.ts, src/SelectionSet/SelectionSet.test-d.ts, src/SelectionSet/toGraphQLDocumentString.test.ts, src/cli/generate.ts, src/client.test.ts, src/entrypoints/alpha/scalars.ts, src/generator/generator.ts, src/lib/graphql.ts, src/raw/lib/graphql.ts, tests/ts/_/schema.graphql, tests/ts/_/schema/Scalar.ts, tests/ts/_/schema/Schema.ts, tests/ts/__snapshots__/generate.test.ts.snap, tests/ts/generate.test.ts
This PR brings primitive support for custom scalars. It permits them to show up in the schema at all, just as strings.
=> feat(ts-client): string support for custom scalars

src/generator/code/code.ts, src/generator/code/scalar.ts, src/generator/code/schemaBuildtime.ts, src/generator/files.ts, src/lib/prelude.ts
This PR makes custom scalars module optional.
=> feat(ts-client): optional custom scalars

src/raw/classes/GraphQLClient.ts, src/raw/helpers/types.ts, tests/raw/general.test.ts
This gives possibility to check request parameters in response middleware and can be used in different scenarios
=> feat: response middleware extra info

src/Schema/core/Index.ts, src/client/Config.ts, src/client/RootTypeMethods.ts, src/client/SelectionSet/_.ts, src/client/SelectionSet/__snapshots__/toGraphQLDocumentString.test.ts.snap, src/client/SelectionSet/toGraphQLDocumentString.test.ts, src/client/SelectionSet/toGraphQLDocumentString.ts, src/client/client.document.test.ts, src/client/client.input.test-d.ts, src/client/client.returnMode.test-d.ts, src/client/client.returnMode.test.ts, src/client/client.ts, src/client/customScalars.ts, src/client/document.ts, src/generator/__snapshots__/files.test.ts.snap, src/generator/code/Index.ts, src/generator/code/SchemaRuntime.ts, src/generator/code/generateCode.ts, src/lib/prelude.ts, tests/_/db.ts, tests/_/schema/generated/Index.ts, tests/_/schema/generated/SchemaRuntime.ts, tests/_/schemaMutationOnly/generated/Index.ts, tests/_/schemaMutationOnly/generated/SchemaRuntime.ts, tests/_/schemaQueryOnly/generated/Index.ts, tests/_/schemaQueryOnly/generated/SchemaRuntime.ts
=> feat(ts-client): returnMode successData

src/legacy/classes/GraphQLClient.ts, src/legacy/helpers/types.ts, src/lib/prelude.ts, tests/legacy/middleware.test.ts
=> fix: await response middleware

src/entrypoints/alpha/main.ts, src/layers/3_SelectionSet/encode.ts, src/layers/5_client/client.test.ts, src/layers/5_client/client.ts
This feature brings an incremental approach to client.
It allows client to incrementally be enhanced from raw to typed.
This is generally elegant library design.
It also provides a natural bridge for existing `graphql-request` users. They should be able to migrate to Graffle in a trivial way, exploring the typed client at their leisure.
=> feat(graffle): incremental typed client

src/layers/5_client/client.extend.test.ts, src/layers/5_client/client.ts, src/lib/anyware/__.test-d.ts, src/lib/anyware/getEntrypoint.ts, src/lib/anyware/lib.ts, src/lib/anyware/main.test.ts, src/lib/anyware/main.ts, src/lib/anyware/runHook.ts, src/lib/anyware/runPipeline.ts, src/lib/prelude.ts
=> feat: anyware hook retries

README.md, package.json, src/layers/2_generator/files.ts
=> fix: make dprint optional dep

src/layers/2_generator/__snapshots__/files.test.ts.snap, src/layers/2_generator/code/Error.ts, src/layers/2_generator/code/Select.ts, src/layers/2_generator/code/global.ts, tests/_/schema/generated/Global.ts, tests/_/schema/generated/Select.ts, tests/_/schemaMutationOnly/generated/Global.ts, tests/_/schemaMutationOnly/generated/Select.ts, tests/_/schemaQueryOnly/generated/Global.ts, tests/_/schemaQueryOnly/generated/Select.ts
=> fix: verbatimModuleSyntax

examples/legacy/other-middleware.ts
Changes spreading request headers to using new Headers object.
Closes #907
=> docs: change spreading request headers to using new Headers

src/layers/2_Select/SelectAlias.ts, src/layers/2_Select/selectionSet.ts, src/layers/3_InferResult/Alias.ts, src/layers/3_InferResult/__.test-d.ts, src/layers/4_generator/__snapshots__/generate.test.ts.snap, src/layers/4_generator/generators/MethodsRoot.ts, src/layers/6_client/Settings/client.create.config.output.test-d.ts, src/layers/6_client/gql/send.ts, src/layers/6_client/handleOutput.ts, src/layers/7_extensions/Introspection/Introspection.ts, src/lib/anyware/hook/public.ts, src/lib/grafaid/typed-document/TypedDocument.test-d.ts, src/lib/grafaid/typed-document/TypedDocument.ts, src/lib/prelude.ts, tests/_/schemas/kitchen-sink/graffle/modules/MethodsRoot.ts, tests/_/schemas/mutation-only/graffle/modules/MethodsRoot.ts, tests/_/schemas/pokemon/graffle/modules/MethodsRoot.ts, tests/_/schemas/query-only/graffle/modules/MethodsRoot.ts, website/graffle/modules/MethodsRoot.ts, website/pokemon/modules/MethodsRoot.ts
=> improve(types): readable result types

.gitignore, eslint.config.js, examples/__outputs__/20_output/output_envelope.output.test.txt, examples/__outputs__/20_output/output_return-error_return-error-execution__return-error-execution.output.txt, package.json, src/documentBuilder/Select/document.ts, src/generator/generators/MethodsRoot.ts, src/layers/5_request/core.ts, src/layers/5_request/hooks.ts, src/layers/6_client/client.ts, src/layers/6_client/gql/gql.ts, src/layers/6_client/handleOutput.ts, src/lib/grafaid/document.ts, src/lib/grafaid/document/OperationTypeNode.ts, src/lib/grafaid/document/OperationTypeNodes.ts, src/lib/grafaid/document/kind.ts, src/lib/grafaid/document/kinds.ts, src/lib/grafaid/graphql.ts, src/lib/grafaid/http/http.ts, tests/e2e/tests.txt
Progresses #1216
The primary changes here:
1. Redefine `Kind` and `OperationTypeNode` enums from GraphQL in a tree-shakable way.
Before (~5000b):
After (~850b):
3. Avoid references to `GraphQLError`. It drags in a lot of the graphql package.
=> feat(perf): remove imports that bloat bundle

src/entrypoints/_Generator.ts, src/extensions/SchemaErrors/documentation.md, src/extensions/SchemaErrors/tests/fixture/graffle.config.ts, src/generator/configFile/builder.ts, website/content/guides/50_appendix/15_about-generation.md
Progresses https://github.com/graffle-js/graffle/issues/1214
=> fix(generator): align exports with docs

src/extensions/SchemaErrors/injectTypenameOnRootResultFields.test.ts, src/extensions/SchemaErrors/tests/fixture/graffle/_.ts, src/extensions/SchemaErrors/tests/fixture/graffle/__.ts, src/generator/generator/__snapshots__/generate.test.ts.snap, src/generator/generators/_.ts, src/generator/generators/__.ts, tests/_/schemas/kitchen-sink/graffle/_.ts, tests/_/schemas/kitchen-sink/graffle/__.ts, tests/_/schemas/mutation-only/graffle/_.ts, tests/_/schemas/mutation-only/graffle/__.ts, tests/_/schemas/pokemon/graffle/_.ts, tests/_/schemas/pokemon/graffle/__.ts, tests/_/schemas/query-only/graffle/_.ts, tests/_/schemas/query-only/graffle/__.ts, website/content/guides/50_appendix/05_custom-scalars.md, website/graffle/_.ts, website/graffle/__.ts, website/pokemon/_.ts, website/pokemon/__.ts
This PR creates consistency between what the generator code exports and the Graffle constructor input. It allows for field punning for one thing, and also reduces terms as seen the code. We still use the more verbose term in our docs and internal code, at least for now.
=> improve(generator): export SDDM term aligning with input

src/entrypoints/extensionkit.ts, src/extension/extension.ts, src/extensions/Introspection/Introspection.ts, src/extensions/SchemaErrors/runtime.ts, src/extensions/Throws/Throws.ts, src/layers/6_client/Settings/InputToConfig.ts, src/layers/6_client/chainExtensions/anyware.ts, src/layers/6_client/chainExtensions/internal.ts, src/layers/6_client/chainExtensions/scalar.ts, src/layers/6_client/chainExtensions/use.test.ts, src/layers/6_client/chainExtensions/use.ts, src/layers/6_client/chainExtensions/with.ts, src/layers/6_client/client.ts, src/layers/6_client/gql/gql.ts, src/layers/6_client/requestMethods/requestMethods.ts, src/lib/chain/__.test-d.ts, src/lib/chain/__.ts, src/lib/config-manager/ConfigManager.ts
This PR makes it possible for extension authors to inline their
type extensions into the extension body. We achieve this with a new
explicit typeHooks field in the constructor input as well as a new
phantom property on builder property to supply types along with a helper
sub-constructor for hiding this nested phantom property.
=> feat(extension): support inline type extensions

src/generator/generators/Scalar.ts
ACTUALLY closes #1228
We need to add one more scalar to the tests to avoid not catching this. Hardcoding to date never broke the tests since they used... Date. 🤦.
Thank you @ziimakc.
=> fix(generator): scalar definition name

package.json, website/content/guides/20_getting-started.md
=> feat(pacakge): support cjs

examples/10_transport-http/transport-http_extension_headers__dynamicHeaders.ts, examples/10_transport-http/transport-http_headers_raw__headers.ts, examples/50_anyware/anyware_jump-start__jump-start.ts, examples/50_anyware/anyware_short-circuit__short-circuit.ts, src/client/builderExtensions/anyware.ts, src/client/builderExtensions/use.test.ts, src/client/client.transport-http.test.ts, src/client/client.transport-memory.test.ts, src/requestPipeline/RequestPipeline.ts, tests/_/SpyExtension.ts
This change removes some ergonomics from the request pipeline anyware in
order to pursue the larger modular request pipeline refactor. We should
be able to bring back even better DX but with a very different approach
by the end.
=> improve(request-pipeline): no conditional type on config

examples/__outputs__/20_output/output_preset__standard-graphql.output.txt, src/lib/anyware/Extension/Builder.ts, src/lib/anyware/Extension/Extension.ts, src/lib/anyware/Extension/__.ts, src/lib/anyware/Overload/Builder.ts, src/lib/anyware/Overload/Overload.ts, src/lib/anyware/Overload/__.ts, src/lib/anyware/Pipeline/builder.test-d.ts, src/lib/anyware/Pipeline/builder.ts, src/lib/anyware/Step.ts, src/lib/anyware/_.ts, src/lib/anyware/run/run.test.ts, src/lib/config-manager/ConfigManager.ts, src/lib/prelude.ts, src/requestPipeline/RequestPipeline.ts, src/requestPipeline/extensions/httpTransport.ts, src/requestPipeline/extensions/memoryTransport.ts
Progresses https://github.com/graffle-js/graffle/issues/1236
This PR brings extensions to anyware. The HTTP and Memory transports are moved to being anyware extensions now. The next step is to lift them one level up into Graffle extensions. This will require the ability to statically apply anyware extensions (should be fairly simple).
=> improve(anyware): extensions

src/context/fragments/extensions/dataType/builder.ts, src/generator/config/config.ts, src/generator/generators/Scalar.test.ts, tests/e2e/__snapshots__/e2e.test.ts.snap
Fixes #1367 - File extensions are being added despite `importFormat: 'noExtension'` configuration.
When `importFormat` was set to `'noExtension'`, the generator was still adding `.js` extensions to:
- Custom scalar imports 
- Library path imports
This issue appeared in versions after 8.0.0-next.140.
Added a helper function `getImportExtension` that properly respects the `importFormat` setting:
- `jsExtension`: Replaces `.ts` with `.js` (default)
- `tsExtension`: Keeps `.ts` extension
- `noExtension`: Removes any extension
Applied this helper to both scalar imports and library path processing.
Added a test case that verifies `noExtension` import format works correctly for custom scalar imports. All existing tests continue to pass.
=> fix(generator): respect importFormat setting for scalars and library paths
